/* eslint-disable no-unused-vars */
/* eslint-disable @typescript-eslint/naming-convention */
// Auto-split per-generation slice of the Pokémon registry (Improvement Item 9).
// Merged back together by `src/common/pokemon-data.ts`, which preserves the
// original public API. Splitting the ~5,200-line dataset into per-generation
// modules prepares it for on-demand (dynamic import) loading.
import {
  PokemonColor,
  PokemonConfig,
  PokemonExtraSprite,
  PokemonGeneration,
} from './types';

export const GEN5_POKEMON: Record<string, PokemonConfig> = {
  victini: {
    id: 494,
    name: 'Victini',
    generation: PokemonGeneration.Gen5,
    cry: 'Victini!',
    possibleColors: [PokemonColor.default],
  },
  snivy: {
    id: 495,
    name: 'Snivy',
    generation: PokemonGeneration.Gen5,
    cry: 'Snivy!',
    possibleColors: [],
  },
  servine: {
    id: 496,
    name: 'Servine',
    generation: PokemonGeneration.Gen5,
    cry: 'Servine!',
    possibleColors: [],
  },
  serperior: {
    id: 497,
    name: 'Serperior',
    generation: PokemonGeneration.Gen5,
    cry: 'Serperior!',
    possibleColors: [],
  },
  tepig: {
    id: 498,
    name: 'Tepig',
    generation: PokemonGeneration.Gen5,
    cry: 'Tepig!',
    possibleColors: [],
  },
  pignite: {
    id: 499,
    name: 'Pignite',
    generation: PokemonGeneration.Gen5,
    cry: 'Pignite!',
    possibleColors: [],
  },
  emboar: {
    id: 500,
    name: 'Emboar',
    generation: PokemonGeneration.Gen5,
    cry: 'Emboar!',
    possibleColors: [],
  },
  oshawott: {
    id: 501,
    name: 'Oshawott',
    generation: PokemonGeneration.Gen5,
    cry: 'Oshawott!',
    possibleColors: [],
  },
  dewott: {
    id: 502,
    name: 'Dewott',
    generation: PokemonGeneration.Gen5,
    cry: 'Dewott!',
    possibleColors: [],
  },
  samurott: {
    id: 503,
    name: 'Samurott',
    generation: PokemonGeneration.Gen5,
    cry: 'Samurott!',
    possibleColors: [],
  },
  patrat: {
    id: 504,
    name: 'Patrat',
    generation: PokemonGeneration.Gen5,
    cry: 'Patrat!',
    possibleColors: [PokemonColor.default],
  },
  watchog: {
    id: 505,
    name: 'Watchog',
    generation: PokemonGeneration.Gen5,
    cry: 'Watchog!',
    possibleColors: [PokemonColor.default],
  },
  lillipup: {
    id: 506,
    name: 'Lillipup',
    generation: PokemonGeneration.Gen5,
    cry: 'Lillipup!',
    possibleColors: [],
  },
  herdier: {
    id: 507,
    name: 'Herdier',
    generation: PokemonGeneration.Gen5,
    cry: 'Herdier!',
    possibleColors: [PokemonColor.default],
  },
  stoutland: {
    id: 508,
    name: 'Stoutland',
    generation: PokemonGeneration.Gen5,
    cry: 'Stoutland!',
    possibleColors: [],
  },
  purrloin: {
    id: 509,
    name: 'Purrloin',
    generation: PokemonGeneration.Gen5,
    cry: 'Purrloin!',
    possibleColors: [],
  },
  liepard: {
    id: 510,
    name: 'Liepard',
    generation: PokemonGeneration.Gen5,
    cry: 'Liepard!',
    possibleColors: [PokemonColor.default],
  },
  pansage: {
    id: 511,
    name: 'Pansage',
    generation: PokemonGeneration.Gen5,
    cry: 'Pansage!',
    possibleColors: [PokemonColor.default],
  },
  simisage: {
    id: 512,
    name: 'Simisage',
    generation: PokemonGeneration.Gen5,
    cry: 'Simisage!',
    possibleColors: [],
  },
  pansear: {
    id: 513,
    name: 'Pansear',
    generation: PokemonGeneration.Gen5,
    cry: 'Pansear!',
    possibleColors: [PokemonColor.default],
  },
  simisear: {
    id: 514,
    name: 'Simisear',
    generation: PokemonGeneration.Gen5,
    cry: 'Simisear!',
    possibleColors: [],
  },
  panpour: {
    id: 515,
    name: 'Panpour',
    generation: PokemonGeneration.Gen5,
    cry: 'Panpour!',
    possibleColors: [PokemonColor.default],
  },
  simipour: {
    id: 516,
    name: 'Simipour',
    generation: PokemonGeneration.Gen5,
    cry: 'Simipour!',
    possibleColors: [],
  },
  munna: {
    id: 517,
    name: 'Munna',
    generation: PokemonGeneration.Gen5,
    cry: 'Munna!',
    possibleColors: [PokemonColor.default],
  },
  musharna: {
    id: 518,
    name: 'Musharna',
    generation: PokemonGeneration.Gen5,
    cry: 'Musharna!',
    possibleColors: [PokemonColor.default],
  },
  pidove: {
    id: 519,
    name: 'Pidove',
    generation: PokemonGeneration.Gen5,
    cry: 'Pidove!',
    possibleColors: [PokemonColor.default],
  },
  tranquill: {
    id: 520,
    name: 'Tranquill',
    generation: PokemonGeneration.Gen5,
    cry: 'Tranquill!',
    possibleColors: [],
  },
  unfezant: {
    id: 521,
    name: 'Unfezant',
    generation: PokemonGeneration.Gen5,
    cry: 'Unfezant!',
    possibleColors: [],
  },
  blitzle: {
    id: 522,
    name: 'Blitzle',
    generation: PokemonGeneration.Gen5,
    cry: 'Blitzle!',
    possibleColors: [],
  },
  zebstrika: {
    id: 523,
    name: 'Zebstrika',
    generation: PokemonGeneration.Gen5,
    cry: 'Zebstrika!',
    possibleColors: [PokemonColor.default],
  },
  roggenrola: {
    id: 524,
    name: 'Roggenrola',
    generation: PokemonGeneration.Gen5,
    cry: 'Roggenrola!',
    possibleColors: [],
  },
  boldore: {
    id: 525,
    name: 'Boldore',
    generation: PokemonGeneration.Gen5,
    cry: 'Boldore!',
    possibleColors: [PokemonColor.default],
  },
  gigalith: {
    id: 526,
    name: 'Gigalith',
    generation: PokemonGeneration.Gen5,
    cry: 'Gigalith!',
    possibleColors: [],
  },
  woobat: {
    id: 527,
    name: 'Woobat',
    generation: PokemonGeneration.Gen5,
    cry: 'Woobat!',
    possibleColors: [PokemonColor.default],
  },
  swoobat: {
    id: 528,
    name: 'Swoobat',
    generation: PokemonGeneration.Gen5,
    cry: 'Swoobat!',
    possibleColors: [],
  },
  drilbur: {
    id: 529,
    name: 'Drilbur',
    generation: PokemonGeneration.Gen5,
    cry: 'Drilbur!',
    possibleColors: [PokemonColor.default],
    extraSprites: [PokemonExtraSprite.leftFacing],
  },
  excadrill: {
    id: 530,
    name: 'Excadrill',
    generation: PokemonGeneration.Gen5,
    cry: 'Excadrill!',
    possibleColors: [],
  },
  audino: {
    id: 531,
    name: 'Audino',
    generation: PokemonGeneration.Gen5,
    cry: 'Audino!',
    possibleColors: [PokemonColor.default],
  },
  timburr: {
    id: 532,
    name: 'Timburr',
    generation: PokemonGeneration.Gen5,
    cry: 'Timburr!',
    possibleColors: [],
  },
  gurdurr: {
    id: 533,
    name: 'Gurdurr',
    generation: PokemonGeneration.Gen5,
    cry: 'Gurdurr!',
    possibleColors: [PokemonColor.default],
  },
  conkeldurr: {
    id: 534,
    name: 'Conkeldurr',
    generation: PokemonGeneration.Gen5,
    cry: 'Conkeldurr!',
    possibleColors: [],
  },
  tympole: {
    id: 535,
    name: 'Tympole',
    generation: PokemonGeneration.Gen5,
    cry: 'Tympole!',
    possibleColors: [PokemonColor.default],
  },
  palpitoad: {
    id: 536,
    name: 'Palpitoad',
    generation: PokemonGeneration.Gen5,
    cry: 'Palpitoad!',
    possibleColors: [],
  },
  seismitoad: {
    id: 537,
    name: 'Seismitoad',
    generation: PokemonGeneration.Gen5,
    cry: 'Seismitoad!',
    possibleColors: [],
  },
  throh: {
    id: 538,
    name: 'Throh',
    generation: PokemonGeneration.Gen5,
    cry: 'Throh!',
    possibleColors: [PokemonColor.default],
  },
  sawk: {
    id: 539,
    name: 'Sawk',
    generation: PokemonGeneration.Gen5,
    cry: 'Sawk!',
    possibleColors: [PokemonColor.default],
    extraSprites: [PokemonExtraSprite.leftFacing],
  },
  sewaddle: {
    id: 540,
    name: 'Sewaddle',
    generation: PokemonGeneration.Gen5,
    cry: 'Sewaddle!',
    possibleColors: [],
  },
  swadloon: {
    id: 541,
    name: 'Swadloon',
    generation: PokemonGeneration.Gen5,
    cry: 'Swadloon!',
    possibleColors: [],
  },
  leavanny: {
    id: 542,
    name: 'Leavanny',
    generation: PokemonGeneration.Gen5,
    cry: 'Leavanny!',
    possibleColors: [PokemonColor.default],
  },
  venipede: {
    id: 543,
    name: 'Venipede',
    generation: PokemonGeneration.Gen5,
    cry: 'Venipede!',
    possibleColors: [],
  },
  whirlipede: {
    id: 544,
    name: 'Whirlipede',
    generation: PokemonGeneration.Gen5,
    cry: 'Whirlipede!',
    possibleColors: [],
  },
  scolipede: {
    id: 545,
    name: 'Scolipede',
    generation: PokemonGeneration.Gen5,
    cry: 'Scolipede!',
    possibleColors: [PokemonColor.default],
  },
  cottonee: {
    id: 546,
    name: 'Cottonee',
    generation: PokemonGeneration.Gen5,
    cry: 'Cottonee!',
    possibleColors: [PokemonColor.default],
  },
  whimsicott: {
    id: 547,
    name: 'Whimsicott',
    generation: PokemonGeneration.Gen5,
    cry: 'Whimsicott!',
    possibleColors: [],
  },
  petilil: {
    id: 548,
    name: 'Petilil',
    generation: PokemonGeneration.Gen5,
    cry: 'Petilil!',
    possibleColors: [PokemonColor.default],
  },
  lilligant: {
    id: 549,
    name: 'Lilligant',
    generation: PokemonGeneration.Gen5,
    cry: 'Lilligant!',
    possibleColors: [],
  },
  basculin_red_striped: {
    id: 550,
    name: 'Basculin (Red-Striped Form)',
    generation: PokemonGeneration.Gen5,
    cry: 'Basculin!',
    possibleColors: [PokemonColor.default],
  },
  basculin_blue_striped: {
    id: 550,
    name: 'Basculin (Blue-Striped Form)',
    generation: PokemonGeneration.Gen5,
    cry: 'Basculin!',
    possibleColors: [PokemonColor.default],
  },
  sandile: {
    id: 551,
    name: 'Sandile',
    generation: PokemonGeneration.Gen5,
    cry: 'Sandile!',
    possibleColors: [],
  },
  krokorok: {
    id: 552,
    name: 'Krokorok',
    generation: PokemonGeneration.Gen5,
    cry: 'Krokorok!',
    possibleColors: [PokemonColor.default],
  },
  krookodile: {
    id: 553,
    name: 'Krookodile',
    generation: PokemonGeneration.Gen5,
    cry: 'Krookodile!',
    possibleColors: [PokemonColor.default],
  },
  darumaka: {
    id: 554,
    name: 'Darumaka',
    generation: PokemonGeneration.Gen5,
    cry: 'Darumaka!',
    possibleColors: [],
  },
  darmanitan: {
    id: 555,
    name: 'Darmanitan',
    generation: PokemonGeneration.Gen5,
    cry: 'Darmanitan!',
    possibleColors: [],
  },
  maractus: {
    id: 556,
    name: 'Maractus',
    generation: PokemonGeneration.Gen5,
    cry: 'Maractus!',
    possibleColors: [PokemonColor.default],
  },
  dwebble: {
    id: 557,
    name: 'Dwebble',
    generation: PokemonGeneration.Gen5,
    cry: 'Dwebble!',
    possibleColors: [],
  },
  crustle: {
    id: 558,
    name: 'Crustle',
    generation: PokemonGeneration.Gen5,
    cry: 'Crustle!',
    possibleColors: [PokemonColor.default],
  },
  scraggy: {
    id: 559,
    name: 'Scraggy',
    generation: PokemonGeneration.Gen5,
    cry: 'Scraggy!',
    possibleColors: [PokemonColor.default],
  },
  scrafty: {
    id: 560,
    name: 'Scrafty',
    generation: PokemonGeneration.Gen5,
    cry: 'Scrafty!',
    possibleColors: [],
  },
  sigilyph: {
    id: 561,
    name: 'Sigilyph',
    generation: PokemonGeneration.Gen5,
    cry: 'Sigilyph!',
    possibleColors: [PokemonColor.default],
  },
  yamask: {
    id: 562,
    name: 'Yamask',
    generation: PokemonGeneration.Gen5,
    cry: 'Yamask!',
    possibleColors: [],
  },
  cofagrigus: {
    id: 563,
    name: 'Cofagrigus',
    generation: PokemonGeneration.Gen5,
    cry: 'Cofagrigus!',
    possibleColors: [],
  },
  tirtouga: {
    id: 564,
    name: 'Tirtouga',
    generation: PokemonGeneration.Gen5,
    cry: 'Tirtouga!',
    possibleColors: [PokemonColor.default],
  },
  carracosta: {
    id: 565,
    name: 'Carracosta',
    generation: PokemonGeneration.Gen5,
    cry: 'Carracosta!',
    possibleColors: [],
  },
  archen: {
    id: 566,
    name: 'Archen',
    generation: PokemonGeneration.Gen5,
    cry: 'Archen!',
    possibleColors: [],
  },
  archeops: {
    id: 567,
    name: 'Archeops',
    generation: PokemonGeneration.Gen5,
    cry: 'Archeops!',
    possibleColors: [],
  },
  trubbish: {
    id: 568,
    name: 'Trubbish',
    generation: PokemonGeneration.Gen5,
    cry: 'Trubbish!',
    possibleColors: [],
  },
  garbodor: {
    id: 569,
    name: 'Garbodor',
    generation: PokemonGeneration.Gen5,
    cry: 'Garbodor!',
    possibleColors: [PokemonColor.default],
    extraSprites: [PokemonExtraSprite.leftFacing],
  },
  zorua: {
    id: 570,
    name: 'Zorua',
    generation: PokemonGeneration.Gen5,
    cry: 'Zorua!',
    possibleColors: [PokemonColor.default],
  },
  zoroark: {
    id: 571,
    name: 'Zoroark',
    generation: PokemonGeneration.Gen5,
    cry: 'Zoroark!',
    possibleColors: [],
  },
  minccino: {
    id: 572,
    name: 'Minccino',
    generation: PokemonGeneration.Gen5,
    cry: 'Minccino!',
    possibleColors: [PokemonColor.default],
  },
  cinccino: {
    id: 573,
    name: 'Cinccino',
    generation: PokemonGeneration.Gen5,
    cry: 'Cinccino!',
    possibleColors: [],
  },
  gothita: {
    id: 574,
    name: 'Gothita',
    generation: PokemonGeneration.Gen5,
    cry: 'Gothita!',
    possibleColors: [],
  },
  gothorita: {
    id: 575,
    name: 'Gothorita',
    generation: PokemonGeneration.Gen5,
    cry: 'Gothorita!',
    possibleColors: [PokemonColor.default],
  },
  gothitelle: {
    id: 576,
    name: 'Gothitelle',
    generation: PokemonGeneration.Gen5,
    cry: 'Gothitelle!',
    possibleColors: [],
  },
  solosis: {
    id: 577,
    name: 'Solosis',
    generation: PokemonGeneration.Gen5,
    cry: 'Solosis!',
    possibleColors: [],
  },
  duosion: {
    id: 578,
    name: 'Duosion',
    generation: PokemonGeneration.Gen5,
    cry: 'Duosion!',
    possibleColors: [PokemonColor.default],
  },
  reuniclus: {
    id: 579,
    name: 'Reuniclus',
    generation: PokemonGeneration.Gen5,
    cry: 'Reuniclus!',
    possibleColors: [],
  },
  ducklett: {
    id: 580,
    name: 'Ducklett',
    generation: PokemonGeneration.Gen5,
    cry: 'Ducklett!',
    possibleColors: [PokemonColor.default],
  },
  swanna: {
    id: 581,
    name: 'Swanna',
    generation: PokemonGeneration.Gen5,
    cry: 'Swanna!',
    possibleColors: [],
  },
  vanillite: {
    id: 582,
    name: 'Vanillite',
    generation: PokemonGeneration.Gen5,
    cry: 'Vanillite!',
    possibleColors: [],
  },
  vanillish: {
    id: 583,
    name: 'Vanillish',
    generation: PokemonGeneration.Gen5,
    cry: 'Vanillish!',
    possibleColors: [PokemonColor.default],
  },
  vanilluxe: {
    id: 584,
    name: 'Vanilluxe',
    generation: PokemonGeneration.Gen5,
    cry: 'Vanilluxe!',
    possibleColors: [],
  },
  deerling_spring: {
    id: 585,
    name: 'Deerling (Spring Form)',
    generation: PokemonGeneration.Gen5,
    cry: 'Deerling!',
    possibleColors: [PokemonColor.default],
  },
  deerling_summer: {
    id: 585,
    name: 'Deerling (Summer Form)',
    generation: PokemonGeneration.Gen5,
    cry: 'Deerling!',
    possibleColors: [PokemonColor.default],
  },
  deerling_autumn: {
    id: 585,
    name: 'Deerling (Autumn Form)',
    generation: PokemonGeneration.Gen5,
    cry: 'Deerling!',
    possibleColors: [PokemonColor.default],
  },
  deerling_winter: {
    id: 585,
    name: 'Deerling (Winter Form)',
    generation: PokemonGeneration.Gen5,
    cry: 'Deerling!',
    possibleColors: [PokemonColor.default],
  },
  sawsbuck_spring: {
    id: 586,
    name: 'Sawsbuck (Spring Form)',
    generation: PokemonGeneration.Gen5,
    cry: 'Sawsbuck!',
    possibleColors: [],
  },
  sawsbuck_summer: {
    id: 586,
    name: 'Sawsbuck (Summer Form)',
    generation: PokemonGeneration.Gen5,
    cry: 'Sawsbuck!',
    possibleColors: [],
  },
  sawsbuck_autumn: {
    id: 586,
    name: 'Sawsbuck (Autumn Form)',
    generation: PokemonGeneration.Gen5,
    cry: 'Sawsbuck!',
    possibleColors: [],
  },
  sawsbuck_winter: {
    id: 586,
    name: 'Sawsbuck (Winter Form)',
    generation: PokemonGeneration.Gen5,
    cry: 'Sawsbuck!',
    possibleColors: [],
  },
  emolga: {
    id: 587,
    name: 'Emolga',
    generation: PokemonGeneration.Gen5,
    cry: 'Emolga!',
    possibleColors: [PokemonColor.default],
  },
  karrablast: {
    id: 588,
    name: 'Karrablast',
    generation: PokemonGeneration.Gen5,
    cry: 'Karrablast!',
    possibleColors: [PokemonColor.default],
  },
  escavalier: {
    id: 589,
    name: 'Escavalier',
    generation: PokemonGeneration.Gen5,
    cry: 'Escavalier!',
    possibleColors: [],
  },
  foongus: {
    id: 590,
    name: 'Foongus',
    generation: PokemonGeneration.Gen5,
    cry: 'Foongus!',
    possibleColors: [],
  },
  amoonguss: {
    id: 591,
    name: 'Amoonguss',
    generation: PokemonGeneration.Gen5,
    cry: 'Amoonguss!',
    possibleColors: [],
  },
  frillish: {
    id: 592,
    name: 'Frillish',
    generation: PokemonGeneration.Gen5,
    cry: 'Frillish!',
    possibleColors: [],
  },
  jellicent: {
    id: 593,
    name: 'Jellicent',
    generation: PokemonGeneration.Gen5,
    cry: 'Jellicent!',
    possibleColors: [],
  },
  alomomola: {
    id: 594,
    name: 'Alomomola',
    generation: PokemonGeneration.Gen5,
    cry: 'Alomomola!',
    possibleColors: [PokemonColor.default],
  },
  joltik: {
    id: 595,
    name: 'Joltik',
    generation: PokemonGeneration.Gen5,
    cry: 'Joltik!',
    possibleColors: [],
  },
  galvantula: {
    id: 596,
    name: 'Galvantula',
    generation: PokemonGeneration.Gen5,
    cry: 'Galvantula!',
    possibleColors: [PokemonColor.default],
  },
  ferroseed: {
    id: 597,
    name: 'Ferroseed',
    generation: PokemonGeneration.Gen5,
    cry: 'Ferroseed!',
    possibleColors: [],
  },
  ferrothorn: {
    id: 598,
    name: 'Ferrothorn',
    generation: PokemonGeneration.Gen5,
    cry: 'Ferrothorn!',
    possibleColors: [],
  },
  klink: {
    id: 599,
    name: 'Klink',
    generation: PokemonGeneration.Gen5,
    cry: 'Klink!',
    possibleColors: [],
  },
  klang: {
    id: 600,
    name: 'Klang',
    generation: PokemonGeneration.Gen5,
    cry: 'Klang!',
    possibleColors: [PokemonColor.default],
    extraSprites: [PokemonExtraSprite.leftFacing],
  },
  klinklang: {
    id: 601,
    name: 'Klinklang',
    generation: PokemonGeneration.Gen5,
    cry: 'Klinklang!',
    possibleColors: [],
  },
  tynamo: {
    id: 602,
    name: 'Tynamo',
    generation: PokemonGeneration.Gen5,
    cry: 'Tynamo!',
    possibleColors: [],
  },
  eelektrik: {
    id: 603,
    name: 'Eelektrik',
    generation: PokemonGeneration.Gen5,
    cry: 'Eelektrik!',
    possibleColors: [],
  },
  eelektross: {
    id: 604,
    name: 'Eelektross',
    generation: PokemonGeneration.Gen5,
    cry: 'Eelektross!',
    possibleColors: [],
  },
  elgyem: {
    id: 605,
    name: 'Elgyem',
    generation: PokemonGeneration.Gen5,
    cry: 'Elgyem!',
    possibleColors: [PokemonColor.default],
  },
  beheeyem: {
    id: 606,
    name: 'Beheeyem',
    generation: PokemonGeneration.Gen5,
    cry: 'Beheeyem!',
    possibleColors: [],
  },
  litwick: {
    id: 607,
    name: 'Litwick',
    generation: PokemonGeneration.Gen5,
    cry: 'Litwick!',
    possibleColors: [PokemonColor.default],
    extraSprites: [PokemonExtraSprite.leftFacing],
  },
  lampent: {
    id: 608,
    name: 'Lampent',
    generation: PokemonGeneration.Gen5,
    cry: 'Lampent!',
    possibleColors: [],
  },
  chandelure: {
    id: 609,
    name: 'Chandelure',
    generation: PokemonGeneration.Gen5,
    cry: 'Chandelure!',
    possibleColors: [],
  },
  axew: {
    id: 610,
    name: 'Axew',
    generation: PokemonGeneration.Gen5,
    cry: 'Axew!',
    possibleColors: [PokemonColor.default],
  },
  fraxure: {
    id: 611,
    name: 'Fraxure',
    generation: PokemonGeneration.Gen5,
    cry: 'Fraxure!',
    possibleColors: [],
  },
  haxorus: {
    id: 612,
    name: 'Haxorus',
    generation: PokemonGeneration.Gen5,
    cry: 'Haxorus!',
    possibleColors: [],
  },
  cubchoo: {
    id: 613,
    name: 'Cubchoo',
    generation: PokemonGeneration.Gen5,
    cry: 'Cubchoo!',
    possibleColors: [PokemonColor.default],
  },
  beartic: {
    id: 614,
    name: 'Beartic',
    generation: PokemonGeneration.Gen5,
    cry: 'Beartic!',
    possibleColors: [],
  },
  cryogonal: {
    id: 615,
    name: 'Cryogonal',
    generation: PokemonGeneration.Gen5,
    cry: 'Cryogonal!',
    possibleColors: [],
  },
  shelmet: {
    id: 616,
    name: 'Shelmet',
    generation: PokemonGeneration.Gen5,
    cry: 'Shelmet!',
    possibleColors: [PokemonColor.default],
  },
  accelgor: {
    id: 617,
    name: 'Accelgor',
    generation: PokemonGeneration.Gen5,
    cry: 'Accelgor!',
    possibleColors: [],
  },
  stunfisk: {
    id: 618,
    name: 'Stunfisk',
    generation: PokemonGeneration.Gen5,
    cry: 'Stunfisk!',
    possibleColors: [PokemonColor.default],
  },
  mienfoo: {
    id: 619,
    name: 'Mienfoo',
    generation: PokemonGeneration.Gen5,
    cry: 'Mienfoo!',
    possibleColors: [PokemonColor.default],
  },
  mienshao: {
    id: 620,
    name: 'Mienshao',
    generation: PokemonGeneration.Gen5,
    cry: 'Mienshao!',
    possibleColors: [],
  },
  druddigon: {
    id: 621,
    name: 'Druddigon',
    generation: PokemonGeneration.Gen5,
    cry: 'Druddigon!',
    possibleColors: [PokemonColor.default],
  },
  golett: {
    id: 622,
    name: 'Golett',
    generation: PokemonGeneration.Gen5,
    cry: 'Golett!',
    possibleColors: [PokemonColor.default],
  },
  golurk: {
    id: 623,
    name: 'Golurk',
    generation: PokemonGeneration.Gen5,
    cry: 'Golurk!',
    possibleColors: [],
  },
  pawniard: {
    id: 624,
    name: 'Pawniard',
    generation: PokemonGeneration.Gen5,
    cry: 'Pawniard!',
    possibleColors: [PokemonColor.default],
  },
  bisharp: {
    id: 625,
    name: 'Bisharp',
    generation: PokemonGeneration.Gen5,
    cry: 'Bisharp!',
    possibleColors: [],
  },
  bouffalant: {
    id: 626,
    name: 'Bouffalant',
    generation: PokemonGeneration.Gen5,
    cry: 'Bouffalant!',
    possibleColors: [PokemonColor.default],
  },
  rufflet: {
    id: 627,
    name: 'Rufflet',
    generation: PokemonGeneration.Gen5,
    cry: 'Rufflet!',
    possibleColors: [],
  },
  braviary: {
    id: 628,
    name: 'Braviary',
    generation: PokemonGeneration.Gen5,
    cry: 'Braviary!',
    possibleColors: [PokemonColor.default],
  },
  vullaby: {
    id: 629,
    name: 'Vullaby',
    generation: PokemonGeneration.Gen5,
    cry: 'Vullaby!',
    possibleColors: [],
  },
  mandibuzz: {
    id: 630,
    name: 'Mandibuzz',
    generation: PokemonGeneration.Gen5,
    cry: 'Mandibuzz!',
    possibleColors: [PokemonColor.default],
  },
  heatmor: {
    id: 631,
    name: 'Heatmor',
    generation: PokemonGeneration.Gen5,
    cry: 'Heatmor!',
    possibleColors: [PokemonColor.default],
    extraSprites: [PokemonExtraSprite.leftFacing],
  },
  durant: {
    id: 632,
    name: 'Durant',
    generation: PokemonGeneration.Gen5,
    cry: 'Durant!',
    possibleColors: [PokemonColor.default],
  },
  deino: {
    id: 633,
    name: 'Deino',
    generation: PokemonGeneration.Gen5,
    cry: 'Deino!',
    possibleColors: [],
  },
  zweilous: {
    id: 634,
    name: 'Zweilous',
    generation: PokemonGeneration.Gen5,
    cry: 'Zweilous!',
    possibleColors: [],
  },
  hydreigon: {
    id: 635,
    name: 'Hydreigon',
    generation: PokemonGeneration.Gen5,
    cry: 'Hydreigon!',
    possibleColors: [],
  },
  larvesta: {
    id: 636,
    name: 'Larvesta',
    generation: PokemonGeneration.Gen5,
    cry: 'Larvesta!',
    possibleColors: [],
  },
  volcarona: {
    id: 637,
    name: 'Volcarona',
    generation: PokemonGeneration.Gen5,
    cry: 'Volcarona!',
    possibleColors: [],
  },
  cobalion: {
    id: 638,
    name: 'Cobalion',
    generation: PokemonGeneration.Gen5,
    cry: 'Cobalion!',
    possibleColors: [PokemonColor.default],
  },
  terrakion: {
    id: 639,
    name: 'Terrakion',
    generation: PokemonGeneration.Gen5,
    cry: 'Terrakion!',
    possibleColors: [PokemonColor.default],
  },
  virizion: {
    id: 640,
    name: 'Virizion',
    generation: PokemonGeneration.Gen5,
    cry: 'Virizion!',
    possibleColors: [PokemonColor.default],
  },
  tornadus: {
    id: 641,
    name: 'Tornadus',
    generation: PokemonGeneration.Gen5,
    cry: 'Tornadus!',
    possibleColors: [],
  },
  thundurus: {
    id: 642,
    name: 'Thundurus',
    generation: PokemonGeneration.Gen5,
    cry: 'Thundurus!',
    possibleColors: [],
  },
  reshiram: {
    id: 643,
    name: 'Reshiram',
    generation: PokemonGeneration.Gen5,
    cry: 'Reshiram!',
    possibleColors: [],
  },
  zekrom: {
    id: 644,
    name: 'Zekrom',
    generation: PokemonGeneration.Gen5,
    cry: 'Zekrom!',
    possibleColors: [],
  },
  landorus: {
    id: 645,
    name: 'Landorus',
    generation: PokemonGeneration.Gen5,
    cry: 'Landorus!',
    possibleColors: [],
  },
  kyurem: {
    id: 646,
    name: 'Kyurem',
    generation: PokemonGeneration.Gen5,
    cry: 'Kyurem!',
    possibleColors: [],
  },
  keldeo: {
    id: 647,
    name: 'Keldeo',
    generation: PokemonGeneration.Gen5,
    cry: 'Keldeo!',
    possibleColors: [PokemonColor.default],
  },
  meloetta: {
    id: 648,
    name: 'Meloetta',
    generation: PokemonGeneration.Gen5,
    cry: 'Meloetta!',
    possibleColors: [PokemonColor.default],
    extraSprites: [PokemonExtraSprite.leftFacing],
  },
  genesect: {
    id: 649,
    name: 'Genesect',
    generation: PokemonGeneration.Gen5,
    cry: 'Genesect!',
    possibleColors: [],
  },
};
